In [1]:
import numpy
L = numpy.array([[2,-1,0,0,-1,0],
                 [-1,3,-1,0,-1,0],
                 [0,-1,2,-1,0,0],
                 [0,0,-1,3,-1,-1],
                 [-1,-1,0,-1,3,0],
                 [0,0,0,-1,0,1]])

In [2]:
L

array([[ 2, -1,  0,  0, -1,  0],
       [-1,  3, -1,  0, -1,  0],
       [ 0, -1,  2, -1,  0,  0],
       [ 0,  0, -1,  3, -1, -1],
       [-1, -1,  0, -1,  3,  0],
       [ 0,  0,  0, -1,  0,  1]])

In [7]:
from numpy.linalg import eig as eigenValuesAndVectors
solution = eigenValuesAndVectors(L)

In [8]:
eigenValues = solution[0]

In [9]:
eigenValues

array([3.33066907e-16, 7.21586391e-01, 1.68256939e+00, 3.00000000e+00,
       3.70462437e+00, 4.89121985e+00])

In [11]:
eigenVectors = solution[1]

In [12]:
eigenVectors

array([[-0.40824829, -0.41486979, -0.50529469,  0.28867513, -0.56702343,
        -0.03232265],
       [-0.40824829, -0.30944167,  0.04026854,  0.28867513,  0.65812747,
        -0.46850031],
       [-0.40824829, -0.0692328 ,  0.75901025,  0.28867513, -0.20514371,
         0.35640753],
       [-0.40824829,  0.22093352,  0.20066454, -0.57735027, -0.30843449,
        -0.56195221],
       [-0.40824829, -0.22093352, -0.20066454, -0.57735027,  0.30843449,
         0.56195221],
       [-0.40824829,  0.79354426, -0.29398409,  0.28867513,  0.11403968,
         0.14441544]])

In [3]:
a = numpy.array([[0,1,0,0,1,0],
                [1,0,1,0,1,0],
                [0,1,0,1,0,0],
                [0,0,1,0,1,1],
                [1,1,0,1,0,0],
                [0,0,0,1,0,0]])

In [4]:
a

array([[0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [12]:
I = numpy.eye(6,dtype=int)
I

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [13]:
aa = a + I
aa

array([[1, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [25]:
a22 = aa.dot(aa)
a22

array([[3, 3, 1, 1, 3, 0],
       [3, 4, 2, 2, 3, 0],
       [1, 2, 3, 2, 2, 1],
       [1, 2, 2, 4, 2, 2],
       [3, 3, 2, 2, 4, 1],
       [0, 0, 1, 2, 1, 2]])

In [27]:
a2 = a.dot(a)
a2

array([[2, 1, 1, 1, 1, 0],
       [1, 3, 0, 2, 1, 0],
       [1, 0, 2, 0, 2, 1],
       [1, 2, 0, 3, 0, 0],
       [1, 1, 2, 0, 3, 1],
       [0, 0, 1, 0, 1, 1]])

In [28]:
a3 = a2.dot(a)
a3

array([[2, 4, 2, 2, 4, 1],
       [4, 2, 5, 1, 6, 2],
       [2, 5, 0, 5, 1, 0],
       [2, 1, 5, 0, 6, 3],
       [4, 6, 1, 6, 2, 0],
       [1, 2, 0, 3, 0, 0]])

In [26]:
ab

array([[0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [6]:
b = numpy.array([[0.33,0.29,0,0,0.29,0],
                [0.29,0.25,0.29,0,0.25,0],
                [0,0.29,0.33,0.29,0,0],
                [0,0,0.29,0.25,0.25,0.35],
                [0.29,0.25,0,0.25,0.25,0],
                [0,0,0,0.35,0,0.5]])

In [7]:
b2 = b.dot(b)
print('b:\n',b)
print('b2:\n',b2)

b:
 [[0.33 0.29 0.   0.   0.29 0.  ]
 [0.29 0.25 0.29 0.   0.25 0.  ]
 [0.   0.29 0.33 0.29 0.   0.  ]
 [0.   0.   0.29 0.25 0.25 0.35]
 [0.29 0.25 0.   0.25 0.25 0.  ]
 [0.   0.   0.   0.35 0.   0.5 ]]
b2:
 [[0.2771 0.2407 0.0841 0.0725 0.2407 0.    ]
 [0.2407 0.2932 0.1682 0.1466 0.2091 0.    ]
 [0.0841 0.1682 0.2771 0.1682 0.145  0.1015]
 [0.0725 0.1466 0.1682 0.3316 0.125  0.2625]
 [0.2407 0.2091 0.145  0.125  0.2716 0.0875]
 [0.     0.     0.1015 0.2625 0.0875 0.3725]]


In [33]:
A = numpy.array([[1,2],[3,4]])

In [35]:
B = A.dot(A)
B

array([[ 7, 10],
       [15, 22]])

In [37]:
C = A*A
C

array([[ 1,  4],
       [ 9, 16]])

In [38]:
D = numpy.array([[2,6,4],
                 [-1,-3,-2],
                 [2,6,4]])
D2 = D.dot(D)
D2

array([[ 6, 18, 12],
       [-3, -9, -6],
       [ 6, 18, 12]])