In [1]:
import numpy
L = numpy.array([[2,-1,0,0,-1,0],
                 [-1,3,-1,0,-1,0],
                 [0,-1,2,-1,0,0],
                 [0,0,-1,3,-1,-1],
                 [-1,-1,0,-1,3,0],
                 [0,0,0,-1,0,1]])

In [2]:
L

array([[ 2, -1,  0,  0, -1,  0],
       [-1,  3, -1,  0, -1,  0],
       [ 0, -1,  2, -1,  0,  0],
       [ 0,  0, -1,  3, -1, -1],
       [-1, -1,  0, -1,  3,  0],
       [ 0,  0,  0, -1,  0,  1]])

In [7]:
from numpy.linalg import eig as eigenValuesAndVectors
solution = eigenValuesAndVectors(L)

In [8]:
eigenValues = solution[0]

In [9]:
eigenValues

array([3.33066907e-16, 7.21586391e-01, 1.68256939e+00, 3.00000000e+00,
       3.70462437e+00, 4.89121985e+00])

In [11]:
eigenVectors = solution[1]

In [12]:
eigenVectors

array([[-0.40824829, -0.41486979, -0.50529469,  0.28867513, -0.56702343,
        -0.03232265],
       [-0.40824829, -0.30944167,  0.04026854,  0.28867513,  0.65812747,
        -0.46850031],
       [-0.40824829, -0.0692328 ,  0.75901025,  0.28867513, -0.20514371,
         0.35640753],
       [-0.40824829,  0.22093352,  0.20066454, -0.57735027, -0.30843449,
        -0.56195221],
       [-0.40824829, -0.22093352, -0.20066454, -0.57735027,  0.30843449,
         0.56195221],
       [-0.40824829,  0.79354426, -0.29398409,  0.28867513,  0.11403968,
         0.14441544]])

In [3]:
a = numpy.array([[0,1,0,0,1,0],
                [1,0,1,0,1,0],
                [0,1,0,1,0,0],
                [0,0,1,0,1,1],
                [1,1,0,1,0,0],
                [0,0,0,1,0,0]])

In [4]:
a

array([[0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [12]:
I = numpy.eye(6,dtype=int)
I

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [13]:
aa = a + I
aa

array([[1, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [25]:
a22 = aa.dot(aa)
a22

array([[3, 3, 1, 1, 3, 0],
       [3, 4, 2, 2, 3, 0],
       [1, 2, 3, 2, 2, 1],
       [1, 2, 2, 4, 2, 2],
       [3, 3, 2, 2, 4, 1],
       [0, 0, 1, 2, 1, 2]])

In [27]:
a2 = a.dot(a)
a2

array([[2, 1, 1, 1, 1, 0],
       [1, 3, 0, 2, 1, 0],
       [1, 0, 2, 0, 2, 1],
       [1, 2, 0, 3, 0, 0],
       [1, 1, 2, 0, 3, 1],
       [0, 0, 1, 0, 1, 1]])

In [28]:
a3 = a2.dot(a)
a3

array([[2, 4, 2, 2, 4, 1],
       [4, 2, 5, 1, 6, 2],
       [2, 5, 0, 5, 1, 0],
       [2, 1, 5, 0, 6, 3],
       [4, 6, 1, 6, 2, 0],
       [1, 2, 0, 3, 0, 0]])

In [26]:
ab

array([[0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [6]:
b = numpy.array([[0.33,0.29,0,0,0.29,0],
                [0.29,0.25,0.29,0,0.25,0],
                [0,0.29,0.33,0.29,0,0],
                [0,0,0.29,0.25,0.25,0.35],
                [0.29,0.25,0,0.25,0.25,0],
                [0,0,0,0.35,0,0.5]])

In [7]:
b2 = b.dot(b)
print('b:\n',b)
print('b2:\n',b2)

b:
 [[0.33 0.29 0.   0.   0.29 0.  ]
 [0.29 0.25 0.29 0.   0.25 0.  ]
 [0.   0.29 0.33 0.29 0.   0.  ]
 [0.   0.   0.29 0.25 0.25 0.35]
 [0.29 0.25 0.   0.25 0.25 0.  ]
 [0.   0.   0.   0.35 0.   0.5 ]]
b2:
 [[0.2771 0.2407 0.0841 0.0725 0.2407 0.    ]
 [0.2407 0.2932 0.1682 0.1466 0.2091 0.    ]
 [0.0841 0.1682 0.2771 0.1682 0.145  0.1015]
 [0.0725 0.1466 0.1682 0.3316 0.125  0.2625]
 [0.2407 0.2091 0.145  0.125  0.2716 0.0875]
 [0.     0.     0.1015 0.2625 0.0875 0.3725]]


In [33]:
A = numpy.array([[1,2],[3,4]])

In [35]:
B = A.dot(A)
B

array([[ 7, 10],
       [15, 22]])

In [37]:
C = A*A
C

array([[ 1,  4],
       [ 9, 16]])

In [38]:
D = numpy.array([[2,6,4],
                 [-1,-3,-2],
                 [2,6,4]])
D2 = D.dot(D)
D2

array([[ 6, 18, 12],
       [-3, -9, -6],
       [ 6, 18, 12]])

In [1]:
search_space = {
                "attention_type": ["gat", "gcn", "cos", "const", "gat_sym", 'linear', 'generalized_linear'],
                'aggregator_type': ["sum", "mean", "max", "mlp", ],
                'activate_function': ["sigmoid", "tanh", "relu", "linear",
                                      "softplus", "leaky_relu", "relu6", "elu"],
                'number_of_heads': [1, 2, 4, 6, 8, 16],
                'hidden_units': [4, 8, 16, 32, 64, 128, 256],
            }

In [8]:
def action_index(action_name):
        key_names = search_space.keys()
        for i, key in enumerate(key_names):
            if action_name == key:
                return i
value = action_index("aggregator_type")
print(value)

1


In [2]:
action_names = list(search_space.keys())
print(action_names)

['attention_type', 'aggregator_type', 'activate_function', 'number_of_heads', 'hidden_units']


In [5]:
action_list = 2*action_names

In [6]:
for block_idx, action_name in enumerate(action_list):
    print(block_idx,action_name)
    

0 attention_type
1 aggregator_type
2 activate_function
3 number_of_heads
4 hidden_units
5 attention_type
6 aggregator_type
7 activate_function
8 number_of_heads
9 hidden_units


In [6]:
import numpy as np

reward = 0.6
a = np.clip(reward, -0.5, 0.5)
a

0.5

In [11]:
import scipy

reward = [0.34,0.32,0.99]
rewards = reward[::-1]
f = scipy.signal.lfilter([1],[1,-1],reward[::-1],axis=0)[::-1]

print(reward)
print(f)

[0.34, 0.32, 0.99]
[1.65 1.31 0.99]


In [1]:
import torch

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

In [17]:
score_0 = [0.56,0.282,0.572,0.169,0.394]
score_4 = [0.634,0.595,0.723,0.646,0.675]
score_9 = [0.653,0.734,0.698,0.727,0.733]

In [4]:
sum_0 = sum(score_0)


1.9770000000000003

In [10]:
import numpy as np

In [20]:
mean_ = sum(score_9)/5
mean_

0.709

In [21]:
std_ = np.std(score_9,ddof=1)
print(std_)

0.03457600323924093


In [23]:
import numpy as np
a = [0.5]
b = [0.1,0.2,0.3]
b_a = np.array(b)
c =a + b_a
print(c)

[0.6 0.7 0.8]


In [26]:
a=[[0.1,0.2],[0.3,0.4],[0.5,0.6],[0.7,0.8]]
k = 2
print(a[-k:])
max_ = np.max(a[-k:])
print(max_)

[[0.5, 0.6], [0.7, 0.8]]
0.8


In [11]:
import numpy as np

a = np.array([0.2,0.2, 0.2,0.2,0.2])
b = np.array([4,4,4,4,4])
a[b] += 1
a

array([0.2, 0.2, 0.2, 0.2, 1.2])